sudo: required
services:
    - docker

before_install:
    - docker build -t andriyze/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true andriyze/docker-react npm run test

deploy:
    edge: true
    provider: elastickbeanstalk
    region: "ca-central-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ca-central-1-717934892882"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
