version: '3'
services: 
    web:
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules # this folder is only inside container
            - .:/app #map current folder to app folder inside container
    tests:
        #tty: true
        #stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules # this folder is only inside container
            - .:/app #map current folder to app folder inside container
        command: ["npm", "run", "test"]